@startuml StatementTokeniser
hide empty description
top to bottom direction
state NewToken
State Parameter: consumes
state Operator: consumes
state CompleteToken
state Error
state TypeOfToken <<choice>>
state ToExit <<choice>>

[*] --> NewToken
NewToken --> TypeOfToken
TypeOfToken --> Parameter : IsAlphaDigit
TypeOfToken --> Operator : IsOperator
TypeOfToken --> Error : else
Parameter --> Parameter : IsAlphaDigit
Parameter --> CompleteToken : else
Operator --> Operator : IsOperator
Operator --> CompleteToken : else
CompleteToken --> ToExit


ToExit --> NewToken : else
ToExit --> [*] : EOF
Error --> [*]
@enduml